// <auto-generated />
using System;
using Herbapedia.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Herbapedia.API.Migrations
{
    [DbContext(typeof(HerbapediaDBContext))]
    [Migration("20250212110204_ActualizacionesVarias2")]
    partial class ActualizacionesVarias2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Herbapedia.Model.CommentModel", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<string>("CommentContent")
                        .HasColumnType("text");

                    b.Property<int?>("CommentCreatorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CommentPlantPlantId")
                        .HasColumnType("integer");

                    b.Property<int?>("CommentPostPostId")
                        .HasColumnType("integer");

                    b.HasKey("CommentId");

                    b.HasIndex("CommentCreatorUserId");

                    b.HasIndex("CommentPlantPlantId");

                    b.HasIndex("CommentPostPostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Herbapedia.Model.MessageModel", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<string>("MessageContent")
                        .HasColumnType("text");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MessageReceiverUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("MessageTransmitterUserId")
                        .HasColumnType("integer");

                    b.HasKey("MessageId");

                    b.HasIndex("MessageReceiverUserId");

                    b.HasIndex("MessageTransmitterUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Herbapedia.Model.PlantModel", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlantId"));

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime>("PlantCreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PlantCreatorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("PlantDescription")
                        .HasColumnType("text");

                    b.Property<int?>("PlantEditorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PlantModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlantName")
                        .HasColumnType("text");

                    b.Property<string>("PlantTips")
                        .HasColumnType("text");

                    b.Property<int>("PlantTypeId")
                        .HasColumnType("integer");

                    b.HasKey("PlantId");

                    b.HasIndex("PlantCreatorUserId");

                    b.HasIndex("PlantEditorUserId");

                    b.HasIndex("PlantTypeId");

                    b.ToTable("Plants");

                    b.HasDiscriminator<string>("Log").HasValue("PlantModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Herbapedia.Model.PlantTypeModel", b =>
                {
                    b.Property<int>("PlantTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlantTypeId"));

                    b.Property<string>("PlantTypeDescription")
                        .HasColumnType("text");

                    b.Property<string>("PlantTypeName")
                        .HasColumnType("text");

                    b.HasKey("PlantTypeId");

                    b.ToTable("PlantTypes");
                });

            modelBuilder.Entity("Herbapedia.Model.PostModel", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<string>("PostContent")
                        .HasColumnType("text");

                    b.Property<int?>("PostCreatorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PostId");

                    b.HasIndex("PostCreatorUserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Herbapedia.Model.RoleModel", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<int>("AdminPage")
                        .HasColumnType("integer");

                    b.Property<int>("ChatPage")
                        .HasColumnType("integer");

                    b.Property<int>("HomePage")
                        .HasColumnType("integer");

                    b.Property<int>("LoginPage")
                        .HasColumnType("integer");

                    b.Property<int>("PlantEditionPage")
                        .HasColumnType("integer");

                    b.Property<int>("PlantLogPage")
                        .HasColumnType("integer");

                    b.Property<int>("PlantPage")
                        .HasColumnType("integer");

                    b.Property<int>("PostPage")
                        .HasColumnType("integer");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("text");

                    b.Property<string>("RoleType")
                        .HasColumnType("text");

                    b.Property<int>("UnregisterPage")
                        .HasColumnType("integer");

                    b.Property<int>("UserPage")
                        .HasColumnType("integer");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Herbapedia.Model.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("UserBirthdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UserCreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.Property<string>("UserLoginName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UserModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<string>("UserPassword")
                        .HasColumnType("text");

                    b.Property<string>("UserPhone")
                        .HasColumnType("text");

                    b.Property<int?>("UserRoleRoleId")
                        .HasColumnType("integer");

                    b.Property<string>("UserSurname")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("UserRoleRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Herbapedia.Model.PlantLogModel", b =>
                {
                    b.HasBaseType("Herbapedia.Model.PlantModel");

                    b.Property<int>("PlantLogId")
                        .HasColumnType("integer");

                    b.HasIndex("PlantLogId");

                    b.HasDiscriminator().HasValue("PlantLog");
                });

            modelBuilder.Entity("Herbapedia.Model.CommentModel", b =>
                {
                    b.HasOne("Herbapedia.Model.UserModel", "CommentCreator")
                        .WithMany()
                        .HasForeignKey("CommentCreatorUserId");

                    b.HasOne("Herbapedia.Model.PlantModel", "CommentPlant")
                        .WithMany("Comments")
                        .HasForeignKey("CommentPlantPlantId");

                    b.HasOne("Herbapedia.Model.PostModel", "CommentPost")
                        .WithMany("Comments")
                        .HasForeignKey("CommentPostPostId");

                    b.Navigation("CommentCreator");

                    b.Navigation("CommentPlant");

                    b.Navigation("CommentPost");
                });

            modelBuilder.Entity("Herbapedia.Model.MessageModel", b =>
                {
                    b.HasOne("Herbapedia.Model.UserModel", "MessageReceiver")
                        .WithMany()
                        .HasForeignKey("MessageReceiverUserId");

                    b.HasOne("Herbapedia.Model.UserModel", "MessageTransmitter")
                        .WithMany()
                        .HasForeignKey("MessageTransmitterUserId");

                    b.Navigation("MessageReceiver");

                    b.Navigation("MessageTransmitter");
                });

            modelBuilder.Entity("Herbapedia.Model.PlantModel", b =>
                {
                    b.HasOne("Herbapedia.Model.UserModel", "PlantCreator")
                        .WithMany()
                        .HasForeignKey("PlantCreatorUserId");

                    b.HasOne("Herbapedia.Model.UserModel", "PlantEditor")
                        .WithMany()
                        .HasForeignKey("PlantEditorUserId");

                    b.HasOne("Herbapedia.Model.PlantTypeModel", "PlantType")
                        .WithMany()
                        .HasForeignKey("PlantTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantCreator");

                    b.Navigation("PlantEditor");

                    b.Navigation("PlantType");
                });

            modelBuilder.Entity("Herbapedia.Model.PostModel", b =>
                {
                    b.HasOne("Herbapedia.Model.UserModel", "PostCreator")
                        .WithMany()
                        .HasForeignKey("PostCreatorUserId");

                    b.Navigation("PostCreator");
                });

            modelBuilder.Entity("Herbapedia.Model.UserModel", b =>
                {
                    b.HasOne("Herbapedia.Model.RoleModel", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleRoleId");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Herbapedia.Model.PlantModel", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Herbapedia.Model.PostModel", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
